import type { Plant } from './types'

export const DEFAULT_PLANTS: Plant[] = [
  { id: 'tomate', name: 'Tomate', emoji: '🍅', color: '#e0534b', spacing: 60, height: 70, light: 'full', soil: 'humus', family: 'nacht-schatten', sow: [2, 4], plant: [5, 6], harvest: [7, 9] },
  { id: 'chili', name: 'Chili', emoji: '🌶️', color: '#d6445c', spacing: 40, height: 40, light: 'full', soil: 'humus', family: 'nacht-schatten', sow: [3, 4], plant: [5, 5], harvest: [7, 9] },
  { id: 'gurke', name: 'Gurke', emoji: '🥒', color: '#4c9c52', spacing: 60, height: 35, light: 'full', soil: 'humus', family: 'kuerbis', sow: [3, 5], plant: [5, 6], harvest: [7, 9] },
  { id: 'paprika', name: 'Paprika', emoji: '🫑', color: '#d0541e', spacing: 45, height: 45, light: 'full', soil: 'humus', family: 'nacht-schatten', sow: [2, 4], plant: [5, 6], harvest: [7, 9] },
  { id: 'zucchini', name: 'Zucchini', emoji: '🥒', color: '#2f7d4a', spacing: 80, height: 40, light: 'full', soil: 'humus', family: 'kuerbis', sow: [3, 5], plant: [5, 6], harvest: [7, 9] },
  { id: 'kartoffel', name: 'Kartoffel', emoji: '🥔', color: '#a3764a', spacing: 35, height: 45, light: 'full', soil: 'sand', family: 'knollengewaeche', sow: [4, 5], plant: [4, 5], harvest: [7, 9] },
  { id: 'salat', name: 'Salat', emoji: '🥬', color: '#6dab4a', spacing: 30, height: 20, light: 'partial', soil: 'humus', family: 'kreuzbluetler', sow: [3, 8], plant: [4, 8], harvest: [6, 10] },
  { id: 'karotte', name: 'Karotte', emoji: '🥕', color: '#e8822e', spacing: 8, height: 20, light: 'partial', soil: 'sand', family: 'knollengewaeche', sow: [4, 7], plant: [4, 7], harvest: [7, 10] },
  { id: 'radieschen', name: 'Radieschen', emoji: '🌶️', color: '#d6445c', spacing: 5, height: 12, light: 'partial', soil: 'sand', family: 'kreuzbluetler', sow: [3, 8], plant: [3, 8], harvest: [4, 9] },
  { id: 'zwiebel', name: 'Zwiebel', emoji: '🧅', color: '#c98d4f', spacing: 10, height: 30, light: 'full', soil: 'loam', family: 'lauch', sow: [2, 3], plant: [3, 5], harvest: [7, 9] },
  { id: 'lauch', name: 'Lauch', emoji: '🥬', color: '#3f8a4a', spacing: 12, height: 40, light: 'full', soil: 'humus', family: 'lauch', sow: [3, 4], plant: [6, 6], harvest: [9, 11] },
  { id: 'knoblauch', name: 'Knoblauch', emoji: '🧄', color: '#cdb9a0', spacing: 12, height: 50, light: 'full', soil: 'sand', family: 'lauch', sow: [9, 10], plant: [9, 11], harvest: [6, 8] },
  { id: 'spinat', name: 'Spinat', emoji: '🌿', color: '#3f7d43', spacing: 20, height: 25, light: 'shade', soil: 'humus', family: 'kreuzbluetler', sow: [3, 7], plant: [3, 7], harvest: [4, 6] },
  { id: 'rote-bete', name: 'Rote Bete', emoji: '🫐', color: '#8e2342', spacing: 15, height: 25, light: 'partial', soil: 'loam', family: 'kreuzbluetler', sow: [4, 7], plant: [4, 7], harvest: [7, 9] },
  { id: 'kohlrabi', name: 'Kohlrabi', emoji: '🥬', color: '#7ba35a', spacing: 25, height: 35, light: 'full', soil: 'humus', family: 'kreuzbluetler', sow: [2, 5], plant: [4, 6], harvest: [6, 8] },
  { id: 'kuerbis', name: 'Kürbis', emoji: '🎃', color: '#e08a1e', spacing: 100, height: 60, light: 'full', soil: 'humus', family: 'kuerbis', sow: [3, 5], plant: [5, 6], harvest: [8, 10] },
  { id: 'erdbeere', name: 'Erdbeere', emoji: '🍓', color: '#d6364c', spacing: 30, height: 20, light: 'partial', soil: 'humus', family: 'malven', sow: [3, 4], plant: [9, 11], harvest: [6, 7] },
  { id: 'sonnenblume', name: 'Sonnenblume', emoji: '🌻', color: '#e8a30f', spacing: 40, height: 180, light: 'full', soil: 'humus', family: 'andere', sow: [4, 5], plant: [4, 5], harvest: [8, 9] },
  { id: 'lavendel', name: 'Lavendel', emoji: '💜', color: '#8a7bb8', spacing: 35, height: 60, light: 'full', soil: 'sand', family: 'lippenbluetler', sow: [4, 6], plant: [4, 6], harvest: [7, 8] },
  { id: 'tulpe', name: 'Tulpe', emoji: '🌷', color: '#d0527a', spacing: 12, height: 30, light: 'full', soil: 'sand', family: 'andere', sow: [10, 11], plant: [10, 11], harvest: [4, 5] },
  { id: 'basilikum', name: 'Basilikum', emoji: '🌿', color: '#3f7d43', spacing: 25, height: 40, light: 'full', soil: 'humus', family: 'lippenbluetler', sow: [3, 5], plant: [3, 5], harvest: [7, 9] },
  { id: 'petersilie', name: 'Petersilie', emoji: '🌿', color: '#4c9c52', spacing: 20, height: 30, light: 'partial', soil: 'humus', family: 'andere', sow: [3, 6], plant: [3, 6], harvest: [6, 9] },
  { id: 'schnittlauch', name: 'Schnittlauch', emoji: '🌱', color: '#2f7d4a', spacing: 15, height: 25, light: 'full', soil: 'humus', family: 'lauch', sow: [4, 5], plant: [4, 5], harvest: [6, 9] },
  { id: 'rosmarin', name: 'Rosmarin', emoji: '🌿', color: '#5a7d3f', spacing: 40, height: 60, light: 'full', soil: 'sand', family: 'lippenbluetler', sow: [4, 6], plant: [4, 6], harvest: [6, 9] },
  { id: 'minze', name: 'Minze', emoji: '🌱', color: '#4a9c5a', spacing: 30, height: 30, light: 'partial', soil: 'humus', family: 'lippenbluetler', sow: [4, 6], plant: [4, 6], harvest: [6, 9] },
  { id: 'thymian', name: 'Thymian', emoji: '🌿', color: '#6a8f3f', spacing: 25, height: 25, light: 'full', soil: 'sand', family: 'lippenbluetler', sow: [4, 6], plant: [4, 6], harvest: [6, 9] },
]
